---
- name: Echoing Vars
  hosts: all
  vars_files:
    - external_vars.yaml
  tasks:
    - name: Echo var
      ansible.builtin.command: /bin/echo "Hello World {{msg_name}}"
      register: response
    - name: Print result
      debug:
        var: response
