---
- name: Web Servers
  hosts: webservers
  become: true
  strategy: free

  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: Ensure apche is running 
      ansible.builtin.service:
        name: httpd
        state: started

- name: Application servers
  hosts: appservers
  become: true

  tasks:
    - name: Ensure postgresql is at the latest version
      ansible.builtin.yum:
        name: postgresql
        state: latest
    - name: Ensure that postgresql is started
      ansible.builtin.service:
        name: postgresql
        state: started
