---
- name: Configure nginx
  hosts: RedHat_group
  become: true
  tasks:
   - name: install nginx
     dnf:
       name=nginx
   - name: install firewalld
     dnf:
       name=firewalld
   - name: copy nginx config file
     copy:
       src: /home/iyanu/index.html1
       dest: /etc/nginx/conf.d
   - name: copy index.html
     copy:
       src: /home/iyanu/index.html
       dest: /usr/share/nginx/html/index.html1
       mode: '0644'
     tags: ['deploy']
   - name: restart nginx
     service:
       name: nginx
       state: restarted
     tags: ['deploy']
   - name: Check status 200 and fail if incorrect page contents
     uri:
       url: http://localhost/index.html1
       return_content: yes
     register: response
     tags: ['deploy']
   - name: Print result
     debug:
       var: response.content
     tags: ['deploy', 'test']

   - name: permit traffic in default zone for http service
     ansible.posix.firewalld:
       service: http
       permanent: true
       state: enabled
   - name: restart firewalld
     service:
       name=firewalld
       state=restarted
